### ISSUE TITLE
Data race: backlight test

### ISSUE THREAD

**Issue by naltun** [Shadowbeetle/skbl#3]
From the conversation at Add Go Report Card to README #1 (merged):

> @Shadowbeetle 
> I only have tests for github.com/Shadowbeetle/skbl/backlight. When I run go test -race github.com/Shadowbeetle/skbl/backlight I get tons of races, but to be honest I have no idea what to make of them. Most of them are either written or read by one of my goroutines, but also accessed by testing.go or strings/reader.go and it doesn't really help me figuring out what causes the race condition, or how to fix it.

**Comment by Shadowbeetle** [comment]
Fixed by cb3ae78. 

Though it adds a ton of Mutex.Lock and Unlock calls, not sure if this is the nicest solution. @naltun would you have some time to give it a look? I'd highly appreciate it.
